<?php

namespace api\controllers\tokopedia;

use api\components\Controller;
use api\components\FormAction;
use api\config\ApiCode;
use api\filters\ContentTypeFilter;
use api\forms\tokopedia\ShopShowCaseForm;

class ShopController extends Controller
{
    public function behaviors()
    {
        $behaviors                        = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['content-type-filter'] = [
            'class'       => ContentTypeFilter::class,
            'contentType' => ContentTypeFilter::TYPE_APPLICATION_JSON,
        ];
        return $behaviors;
    }

    public function actions()
    {
        return [
            'showcase' => [
                'class'          => FormAction::className(),
                'formClass'      => ShopShowCaseForm::className(),
                'apiCodeSuccess' => ApiCode::DEFAULT_SUCCESS_CODE,
                'apiCodeFailed'  => ApiCode::DEFAULT_FAILED_CODE,
            ],
        ];
    }

    protected function verbs()
    {
        return [
            'showcase' => ['post'],
        ];
    }
}
