<?php

namespace api\controllers;


use api\components\Controller;
use api\components\FormAction;
use api\filters\ContentTypeFilter;
use api\forms\NotificationForm;

class Shop extends Controller
{
    public function behaviors()
    {
        $behaviors                        = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['content-type-filter'] = [
            'class'       => ContentTypeFilter::class,
            'contentType' => ContentTypeFilter::TYPE_APPLICATION_JSON,
        ];
        return $behaviors;
    }

    public function actions()
    {
        return [
            'showcase' => [
                'class'          => FormAction::className(),
                'formClass'      => NotificationForm::className(),
                'formConfig'     => ['mode' => NotificationForm::MODE_SMS],
                'apiCodeSuccess' => 1,
                'apiCodeFailed'  => 0,
            ],
        ];
    }

    protected function verbs()
    {
        return [
            'showcase' => ['post'],
        ];
    }
}